### ISSUE TITLE
how to load <style> with less-loader when 'lang' lacks?

### ISSUE THREAD

**Issue by DophinL** [vuejs/vue-loader-example#54]
I saw [advanced loader configuration](http://vuejs.github.io/vue-loader/configurations/advanced.html)

but there isn't a method for `<style>`

do we have?

**Comment by yyx990803** [comment]
It work for any lang.

``` js
vue: {
  less: 'css!less'
}
```

**Comment by DophinL** [comment]
Thanks for reply
but it seems not work,here is my `webpack.config.js`:
```javascript
// webpack.config.js
var path = require('path');
var webpack = require('webpack')

var production = (process.env.NODE_ENV == 'production');

var plugins = [new webpack.DefinePlugin({
    'process.env': {
        NODE_ENV: JSON.stringify(process.env.NODE_ENV)
    }
})]

if (production) {
    plugins = plugins.concat([new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false
            }
        }), // optimize module ids by occurence count
        new webpack.optimize.OccurenceOrderPlugin()
    ])
}

var config = {
    devtool: production ? 'source-map' : 'eval',
    // entry point of our application
    entry: './src/main.js',
    // where to place the compiled bundle
    output: {
        path: path.resolve(__dirname, 'build'),
        publicPath: '/build/',
        filename: 'bundle.js'
    },
    module: {
        // `loaders` is an array of loaders to use.
        // here we are only configuring vue-loader
        loaders: [{
            test: /\.vue$/, // a regex for matching all files that end in `.vue`
            loader: 'vue' // loader to use for matched files
        }, {
            test: /\.(png|jpg|gif)$/,
            loader: 'url',
            query: {
                // limit for base64 inlining in bytes
                limit: 10000,
                // custom naming format if file is larger than
                // the threshold
                name: '[name].[ext]?[hash]' //用于file-loader的name
            }
        }, {
            test: /\.js$/,
            loader: 'babel',
            // make sure to exclude 3rd party code in node_modules
            exclude: /node_modules/
        }]
    },
    plugins: plugins,
    vue: {
        less: 'css!less'
    }
}

module.exports = config;
```

`x.vue`
```html
<template src="./Todomvc.html"></template>

<script src="./Todomvc.js"></script>

<style src="./Todomvc.less"></style>
```

`x.less`
```less
// this is just part of them
.todoapp {
	background: #fff;
	margin: 130px 0 40px 0;
	position: relative;
	box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.2),
	            0 25px 50px 0 rgba(0, 0, 0, 0.1);
	h1 {
		position: absolute;
		top: -155px;
		width: 100%;
		font-size: 100px;
		font-weight: 100;
		text-align: center;
		color: rgba(175, 47, 47, 0.15);
		-webkit-text-rendering: optimizeLegibility;
		-moz-text-rendering: optimizeLegibility;
		text-rendering: optimizeLegibility;
	}
}
```

when I enter `webpack-dev-server --inline --hot`,no error show in console
but the result is:
<img width="485" alt="vue less loader" src="https://cloud.githubusercontent.com/assets/8707316/14734606/2e715f18-089e-11e6-88b6-bbbbb073908b.png">
